// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqzxoxdbuhkxazzpjnth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xenhveGRidWhreGF6enBqbnRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNTg5MzAsImV4cCI6MjA3MDczNDkzMH0.5hHELIML696uZDXPmyb0i1mFs1dmnmoxHob4yu9arUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});